### ISSUE TITLE
when will be next translated release?

### ISSUE THREAD

**Issue by 97mathi** [TushBT/InfinityMageNovel#1]
your translation are good, i love it. How frequently do you release the translated version? when will be the next translation? or if you have tool to translate as good as you please mention it Thank you

**Comment by TushBT** [comment]
It is already translated see 1- 51 volumes https://github.com/TushBT/InfinityMageNovel/tree/main/Infinity%20Mage%201-51%20Translated

To translate/contribute just open txt file in chrome browser and right click and click translate to English.
